# Generated by Django 4.1.3 on 2022-12-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='name',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(default=1, upload_to='BannerImage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='titel',
            field=models.CharField(max_length=150),
        ),
    ]
