# Generated by Django 4.1.3 on 2022-12-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_banner_name_banner_image_alter_banner_titel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='CatagoryImages')),
                ('pretn_catagory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.catagory')),
            ],
            options={
                'verbose_name': 'Catagorys',
                'verbose_name_plural': 'Catagorys',
            },
        ),
    ]
