# Generated by Django 4.1.3 on 2022-12-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='BrandImages')),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'Brands',
            },
        ),
    ]
