# Generated by Django 4.1.3 on 2022-12-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diccription', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'About-Us',
            },
        ),
    ]
