# Generated by Django 4.1.3 on 2022-12-05 03:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='diccription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
