# Generated by Django 4.1.3 on 2022-12-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_about_diccription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='diccription',
            new_name='discription',
        ),
    ]
