# Generated by Django 4.1.3 on 2022-12-05 08:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_prodact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodact',
            name='aditional_discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
