# Generated by Django 4.1.3 on 2022-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_catagory_image_alter_catagory_pretn_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='image',
            field=models.ImageField(default=1, upload_to='CatagoryImages'),
            preserve_default=False,
        ),
    ]
